/**
 * ReportFooter Component
 * 레포트 하단 푸터 (액션 아이템, 생성 정보)
 */

import React from 'react';
import { ArrowRight, Globe, Mail, HelpCircle } from 'lucide-react';
import type { ReportFooterProps } from '../../types/reportV3UI.types';

export const ReportFooter: React.FC<ReportFooterProps> = ({
  nextSteps,
  generatedAt,
  isExportMode = false,
  contactInfo,
  className = ''
}) => {
  // 생성 시간 포맷팅
  const formatGeneratedTime = (date: Date | string) => {
    const dateObj = date instanceof Date ? date : new Date(date);
    if (isNaN(dateObj.getTime())) {
      return new Intl.DateTimeFormat('ko-KR', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
      }).format(new Date());
    }
    return new Intl.DateTimeFormat('ko-KR', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    }).format(dateObj);
  };

  return (
    <footer className={`report-footer ${className}`}>
      <div className="report-footer-content">
        {/* 왼쪽: 다음 단계 액션 아이템 */}
        <div className="report-footer-steps">
          <h4 className="report-heading-4 mb-3 text-neutral-dark">
            권장 다음 단계
          </h4>

          {nextSteps.length > 0 ? (
            <div className="space-y-2">
              {nextSteps.slice(0, 3).map((step, index) => (
                <div key={index} className="flex items-start gap-3">
                  <div className="flex-shrink-0 w-6 h-6 bg-primary-main text-white rounded-full flex items-center justify-center text-xs font-semibold mt-0.5">
                    {index + 1}
                  </div>
                  <div className="flex-1">
                    <p className="report-body text-neutral-secondary leading-relaxed">
                      {step}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-muted">
              <p className="report-body">
                현재 수준을 유지하며 지속적인 모니터링을 권장합니다.
              </p>
            </div>
          )}

          {/* 추가 분석 안내 */}
          {!isExportMode && (
            <div className="mt-4 p-3 bg-blue-50 rounded-lg border border-blue-100">
              <div className="flex items-center gap-2 mb-1">
                <ArrowRight size={16} className="text-blue-600" />
                <span className="report-caption font-medium text-blue-900">
                  더 상세한 분석이 필요하시다면?
                </span>
              </div>
              <p className="report-small text-blue-700">
                개별 KPI 상세 분석 및 맞춤 액션플랜을 확인해보세요.
              </p>
            </div>
          )}
        </div>

        {/* 오른쪽: 생성 정보 및 연락처 */}
        <div className="report-footer-meta">
          {/* 생성 정보 */}
          <div className="mb-4">
            <div className="report-small text-muted mb-1">
              리포트 생성 시간
            </div>
            <div className="report-caption font-medium">
              {formatGeneratedTime(generatedAt)}
            </div>
          </div>

          {/* 플랫폼 크레딧 */}
          <div className="mb-4">
            <div className="report-small text-muted mb-1">
              Generated by
            </div>
            <div className="report-caption font-semibold text-primary-main">
              🚀 PocketBiz Platform
            </div>
            <div className="report-small text-muted">
              KPI Diagnosis System v3.0
            </div>
          </div>

          {/* 연락처 정보 */}
          {contactInfo && (
            <div className="space-y-2">
              {contactInfo.website && (
                <div className="flex items-center gap-2">
                  <Globe size={14} className="text-muted" />
                  <a
                    href={contactInfo.website}
                    className="report-small text-primary-main hover:text-primary-dark transition-colors"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    {contactInfo.website.replace(/^https?:\/\//, '')}
                  </a>
                </div>
              )}

              {contactInfo.email && (
                <div className="flex items-center gap-2">
                  <Mail size={14} className="text-muted" />
                  <a
                    href={`mailto:${contactInfo.email}`}
                    className="report-small text-primary-main hover:text-primary-dark transition-colors"
                  >
                    {contactInfo.email}
                  </a>
                </div>
              )}

              {contactInfo.support && (
                <div className="flex items-center gap-2">
                  <HelpCircle size={14} className="text-muted" />
                  <span className="report-small text-muted">
                    {contactInfo.support}
                  </span>
                </div>
              )}
            </div>
          )}

          {/* PDF 모드에서 페이지 정보 */}
          {isExportMode && (
            <div className="mt-4 pt-3 border-t border-gray-200">
              <div className="report-small text-muted text-center">
                Page 1 of 1
              </div>
            </div>
          )}
        </div>
      </div>

      {/* 출력 전용 면책조항 */}
      {isExportMode && (
        <div className="mt-4 pt-4 border-t border-gray-200">
          <p className="report-small text-muted text-center leading-relaxed">
            본 진단 결과는 입력하신 정보를 바탕으로 생성된 참고 자료입니다.
            실제 비즈니스 의사결정 시에는 전문가와의 상담을 권장합니다.
          </p>
        </div>
      )}
    </footer>
  );
};